WHITE_LIST = r"../data/white_list.json"
CHECK_LIST_WHITE = r"../data/check_list_white.json"
CHECK_LIST_BLACK = r"../data/check_list_black.json"
OBSCENE_CORPUS = r"../data/obscene_corpus.json"
THREATS_CORPUS = r"../data/threats_corpus.json"
